// Render the window ground colours main.js needs before any CSS has loaded.
// Kept as a tiny generated ESM module so the main process never carries a
// hand-copied hex that can drift from the theme.

const HEADER = `// GENERATED by desktop/scripts/sync-tokens.mjs from app/src/theme.ts.
// Do not edit by hand — run \`npm run sync-tokens\`.
//
// The colour Electron paints behind each window before the renderer loads,
// so the first frame is already the right ground instead of a white flash:
// the page ground of each of the four appearances, and the machine black a
// stream sits on.`;

/**
 * `{ harbour, night, current, fieldwork, machine }` — the page ground per
 * appearance (src/look.js names) and the ground behind the stream, which is
 * the night machine black whatever the look: the machine panel is dark.
 */
export const groundFromTheme = (theme) =>
  Object.freeze({
    harbour: theme.harbourPalette.bg,
    night: theme.harbourNightPalette.bg,
    current: theme.currentPalette.bg,
    fieldwork: theme.fieldworkPalette.bg,
    machine: theme.harbourNightPalette.machine,
  });

export function renderGroundJs(theme) {
  const entries = Object.entries(groundFromTheme(theme)).map(([key, value]) => `  ${key}: '${value}',`);
  return `${HEADER}\nexport const GROUND = Object.freeze({\n${entries.join('\n')}\n});\n`;
}
