// Render the window ground colours main.js needs before any CSS has loaded.
// Kept as a tiny generated ESM module so the main process never carries a
// hand-copied hex that can drift from the theme.

const HEADER = `// GENERATED by desktop/scripts/sync-tokens.mjs from app/src/theme.ts.
// Do not edit by hand — run \`npm run sync-tokens\`.
//
// The colour Electron paints behind each window before the renderer loads,
// so the first frame is already the right ground instead of a white flash.
// \`darkFirst\` mirrors the app's DARK_FIRST: when true the page windows
// commit to the dark ground whatever the OS says, as the phone does.`;

/**
 * `{ light, dark, machine, darkFirst }` — the page ground per scheme, the
 * ground behind the stream, and whether the product pins itself to dark.
 * The stream ground is the dark palette's machine black in both schemes:
 * the machine panel is dark whatever the OS says.
 */
export const groundFromTheme = (theme, darkFirst) =>
  Object.freeze({
    light: theme.lightPalette.bg,
    dark: theme.darkPalette.bg,
    machine: theme.darkPalette.machine,
    darkFirst,
  });

const literal = (value) => (typeof value === 'string' ? `'${value}'` : String(value));

export function renderGroundJs(theme, darkFirst) {
  const ground = groundFromTheme(theme, darkFirst);
  const entries = Object.entries(ground).map(([key, value]) => `  ${key}: ${literal(value)},`);
  return `${HEADER}\nexport const GROUND = Object.freeze({\n${entries.join('\n')}\n});\n`;
}
