// Render app/src/theme.ts as CSS custom properties — pure, so the test can
// regenerate the stylesheet and compare it with what is on disk.
//
// Naming: every theme key becomes a kebab-case custom property with a short
// group prefix (`--space-md`, `--radius-sm`, `--type-label-size`, …), except
// the palette, whose roles are used everywhere and stay bare (`--bg`,
// `--text-dim`, `--on-machine`). Numbers that are lengths get `px`; the
// phone's pt and a CSS px are the same logical unit.

const HEADER = `/* GENERATED by desktop/scripts/sync-tokens.mjs from app/src/theme.ts.
   Do not edit by hand — run \`npm run sync-tokens\`; test/tokens.test.mjs
   fails when this file and the theme disagree.

   The phone's Ledger tokens, as CSS. Two palettes, one language: light is
   "paper", dark is "ink". The dark palette applies under
   prefers-color-scheme: dark and whenever the root carries
   data-theme="dark"; data-theme="light" pins paper regardless of the OS. */`;

/** `surfaceAlt` → `surface-alt`, `onMachineDim` → `on-machine-dim`. */
export const kebab = (key) => key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const px = (value) => `${value}px`;
const ms = (value) => `${value}ms`;

const declaration = (name, value) => `  --${name}: ${value};`;

const block = (selector, declarations) => `${selector} {\n${declarations.join('\n')}\n}`;

const indent = (text) => text.split('\n').map((line) => (line === '' ? line : `  ${line}`)).join('\n');

/** One palette as bare `--role` properties, in the theme's own key order. */
export const paletteDeclarations = (palette) =>
  Object.entries(palette).map(([role, value]) => declaration(kebab(role), value));

/** The four Outfit weights the app loads; anything heavier falls to 700. */
export const OUTFIT_FACES = Object.freeze([
  Object.freeze({ weight: 400, file: 'Outfit_400Regular.ttf' }),
  Object.freeze({ weight: 500, file: 'Outfit_500Medium.ttf' }),
  Object.freeze({ weight: 600, file: 'Outfit_600SemiBold.ttf' }),
  Object.freeze({ weight: 700, file: 'Outfit_700Bold.ttf' }),
]);

const fontFace = ({ weight, file }) =>
  `@font-face {\n  font-family: "Outfit";\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: block;\n  src: url("fonts/${file}") format("truetype");\n}`;

/** The sans stack: the app's family first, then the platform faces behind it. */
export const sansStack = (font) => `"${font.sans}", -apple-system, "Segoe UI", system-ui, sans-serif`;

const fontDeclarations = (font) => [
  declaration('sans', sansStack(font)),
  declaration('mono', font.mono),
];

const typeDeclarations = (type) =>
  Object.entries(type).flatMap(([variant, style]) => {
    const name = `type-${kebab(variant)}`;
    const family = style.fontFamily === 'Outfit' ? 'var(--sans)' : 'var(--mono)';
    return [
      declaration(`${name}-family`, family),
      declaration(`${name}-size`, px(style.fontSize)),
      declaration(`${name}-line`, px(style.lineHeight)),
      declaration(`${name}-weight`, style.fontWeight ?? '400'),
      declaration(`${name}-tracking`, px(style.letterSpacing ?? 0)),
      declaration(`${name}-transform`, style.textTransform ?? 'none'),
      declaration(`${name}-numerals`, style.fontVariant?.includes('tabular-nums') ? 'tabular-nums' : 'normal'),
    ];
  });

const scaleDeclarations = (prefix, scale) =>
  Object.entries(scale).map(([key, value]) => declaration(`${prefix}-${kebab(key)}`, px(value)));

const layoutDeclarations = (layout) => [
  declaration('min-touch', px(layout.minTouch)),
  declaration('hairline', px(layout.hairline)),
  declaration('rule', px(layout.ruleEmphasis)),
  declaration('margin', px(layout.margin)),
  declaration('row-height', px(layout.rowHeight)),
  declaration('content-max-width', px(layout.contentMaxWidth)),
  declaration('hit-slop', px(layout.hitSlop.top)),
];

const easingValue = (curve) =>
  curve.kind === 'linear' ? 'linear' : `cubic-bezier(${curve.points.join(', ')})`;

const motionDeclarations = (motion, easing) => [
  declaration('motion-instant', ms(motion.instant)),
  declaration('motion-fast', ms(motion.fast)),
  declaration('motion-base', ms(motion.base)),
  declaration('motion-slow', ms(motion.slow)),
  declaration('motion-draw', ms(motion.draw)),
  declaration('press-opacity', String(motion.pressOpacity)),
  declaration('ease-standard', easingValue(easing.standard)),
  declaration('ease-exit', easingValue(easing.exit)),
  declaration('ease-linear', easingValue(easing.linear)),
];

/** The stream HUD's scrim inks (app/src/screen/parts.tsx `HUD`). */
export const hudDeclarations = (hud) =>
  Object.entries(hud).map(([key, value]) => declaration(`hud-${kebab(key)}`, value));

/**
 * The whole stylesheet. `theme` is the evaluated theme module; `hud` is the
 * HUD ink set the stream chrome floats on.
 */
export function renderTokensCss(theme, hud) {
  const dark = paletteDeclarations(theme.darkPalette);
  const sections = [
    HEADER,
    OUTFIT_FACES.map(fontFace).join('\n\n'),
    block(':root', [
      '  color-scheme: light dark;',
      '',
      '  /* palette — light, "paper" */',
      ...paletteDeclarations(theme.lightPalette),
      '',
      '  /* type: mono is the computer speaking, sans is Belay speaking */',
      ...fontDeclarations(theme.font),
      ...typeDeclarations(theme.type),
      '',
      '  /* spacing — strict 4pt base */',
      ...scaleDeclarations('space', theme.space),
      '',
      '  /* radii */',
      ...scaleDeclarations('radius', theme.radius),
      '',
      '  /* layout */',
      ...layoutDeclarations(theme.layout),
      '',
      '  /* motion — ease-out only, nothing over --motion-slow */',
      ...motionDeclarations(theme.motion, theme.easing),
      '',
      '  /* the stream HUD scrim inks (parts.tsx HUD) */',
      ...hudDeclarations(hud),
    ]),
    `/* palette — dark, "ink". The OS setting, unless data-theme pins it. */\n@media (prefers-color-scheme: dark) {\n${indent(block(':root:not([data-theme="light"])', dark))}\n}`,
    block(':root[data-theme="dark"]', dark),
  ];
  return `${sections.join('\n\n')}\n`;
}

/**
 * Read the custom properties back out of a stylesheet, per selector block,
 * so a test can name the exact token that drifted instead of diffing 300
 * lines. Returns `{ [selector]: { [property]: value } }`.
 */
export function parseTokensCss(css) {
  const blocks = {};
  const blockPattern = /([^{}]+)\{([^{}]*)\}/g;
  for (const match of css.matchAll(blockPattern)) {
    const selector = match[1].trim().split('\n').pop().trim();
    if (!selector.startsWith(':root')) continue;
    const declarations = Object.fromEntries(
      [...match[2].matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)].map(([, name, value]) => [name, value.trim()]),
    );
    blocks[selector] = { ...(blocks[selector] ?? {}), ...declarations };
  }
  return blocks;
}
