// GENERATED by desktop/scripts/sync-tokens.mjs from app/src/theme.ts.
// Do not edit by hand — run `npm run sync-tokens`.
//
// The colour Electron paints behind each window before the renderer loads,
// so the first frame is already the right ground instead of a white flash.
// `darkFirst` mirrors the app's DARK_FIRST: when true the page windows
// commit to the dark ground whatever the OS says, as the phone does.
export const GROUND = Object.freeze({
  light: '#F6F8FB',
  dark: '#0A0A0C',
  machine: '#000000',
  darkFirst: true,
});
