# Install (or remove) the Tether host agent as a Windows scheduled task, so the
# machine is reachable from your phone whenever it is awake and logged in.
#
# Usage:
#   npm run autostart            install and start
#   npm run autostart -- status  show whether it is running
#   npm run autostart -- remove  stop and uninstall
#
# Why "run only when the user is logged on"
# -----------------------------------------
# The tempting option is "Run whether user is logged on or not". It is a trap.
# That mode performs a batch logon with no interactive desktop, so the task ends
# up in Session 0 on the Service-0x0-3e7$ window station rather than
# WinSta0\Default. From there SendInput cannot reach the interactive desktop and
# screen capture returns nothing — the agent starts, reports healthy, and every
# screen and input call silently fails.
#
# So the agent runs in the interactive session, which means it starts at logon
# rather than at boot. For an unattended restart to leave the machine reachable,
# enable automatic logon and set the power plan to never sleep.

[CmdletBinding()]
param(
    [ValidateSet('install', 'status', 'remove')]
    [string]$Action = 'install'
)

$ErrorActionPreference = 'Stop'

$TaskName  = 'TetherHostAgent'
$ServerDir = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Get-TetherTask {
    Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
}

switch ($Action) {
    'status' {
        $task = Get-TetherTask
        if ($null -eq $task) {
            Write-Host 'Tether autostart: not installed'
        }
        else {
            $info = Get-ScheduledTaskInfo -TaskName $TaskName
            Write-Host 'Tether autostart: INSTALLED'
            Write-Host "  State        : $($task.State)"
            Write-Host "  Last run     : $($info.LastRunTime)"
            Write-Host "  Last result  : $($info.LastTaskResult)"
        }
        return
    }
    'remove' {
        if ($null -ne (Get-TetherTask)) {
            Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
            Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
            Write-Host "Removed scheduled task '$TaskName'"
        }
        else {
            Write-Host 'Nothing to remove.'
        }
        Write-Host 'Your pairings are untouched - they live in the agent state file.'
        return
    }
}

# --- install ---------------------------------------------------------------

$npm = (Get-Command npm.cmd -ErrorAction SilentlyContinue) ??
       (Get-Command npm -ErrorAction SilentlyContinue)
if ($null -eq $npm) {
    throw 'npm is not on PATH; install Node before setting up autostart.'
}

Write-Host "==> Server directory : $ServerDir"
Write-Host "==> npm              : $($npm.Source)"

# A plain `npm start` opens a console window at every logon. Launching through
# wscript with a one-line VBS shim starts it hidden instead; Task Scheduler has
# no setting that reliably suppresses a child console on its own.
$launcher = Join-Path $ServerDir 'scripts\start-hidden.vbs'
@"
' Starts the Tether host agent with no visible console window.
' Generated by autostart-windows.ps1 - safe to delete when uninstalling.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$ServerDir"
shell.Run "cmd /c ""$($npm.Source)"" start", 0, False
"@ | Set-Content -Path $launcher -Encoding ASCII

Write-Host "==> Wrote $launcher"

if ($null -ne (Get-TetherTask)) {
    Write-Host '==> Removing the existing task first'
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action    = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$launcher`""
$trigger   = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
# Interactive, not S4U or Service: this must land on WinSta0\Default or screen
# capture and input injection both fail. RunLevel Highest avoids a prompt at
# trigger time; it does NOT grant uiAccess, so elevated windows and the UAC
# secure desktop remain out of reach by design.
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
                                        -LogonType Interactive `
                                        -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
                                          -DontStopIfGoingOnBatteries `
                                          -StartWhenAvailable `
                                          -RestartCount 3 `
                                          -RestartInterval (New-TimeSpan -Minutes 1) `
                                          -ExecutionTimeLimit ([TimeSpan]::Zero)

Register-ScheduledTask -TaskName $TaskName `
                       -Action $action `
                       -Trigger $trigger `
                       -Principal $principal `
                       -Settings $settings `
                       -Description 'Runs the Tether host agent so this PC is reachable from the Tether app.' | Out-Null

Write-Host "==> Registered scheduled task '$TaskName'"

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 2
$info = Get-ScheduledTaskInfo -TaskName $TaskName
Write-Host ''
Write-Host 'Tether will now start automatically when you log in.'
Write-Host "  Last result: $($info.LastTaskResult)  (0 means started cleanly)"

Write-Host @'

Two things to know
------------------
1. Windows Defender may flag the input helper the first time it injects
   keystrokes. It is a locally compiled binary, not downloaded - see
   docs/SETUP.md for the exclusion steps.

2. This starts at logon, not at boot. For an unattended restart to leave the
   machine reachable, enable automatic logon and set the power plan to never
   sleep. Also run `powercfg /h off` to disable Fast Startup, which otherwise
   makes a "shutdown" a hibernate that never re-runs logon tasks.

   npm run autostart -- status    is it running
   npm run autostart -- remove    undo all of this
'@
